# Generated by Django 2.1.7 on 2019-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190331_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
